import { StyleSheet } from "react-native";
import globals from "../../../../globalStyles/globals";

export const styles = StyleSheet.create({
  adminAddAssignment: {
    paddingHorizontal: 20,
    position: "relative",
  },
  subjectCode: {
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 20,
    marginBottom: 20,
    backgroundColor: "#fff",
    borderRadius: 10,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 1,
    padding: 10,
  },
  pickerContainer: {
    width: "100%",
    backgroundColor: "#fff",
    borderRadius: 10,
    paddingHorizontal: 10,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 1,
  },
  lableText: {
    fontFamily: globals.titleText.fontFamily,
    fontSize: 18,
    color: "#000",
    marginRight: 10,
    marginTop: 10,
  },
  assignmentDetails: {
    marginTop: 20,
    marginBottom: 20,
    backgroundColor: "#fff",
    borderRadius: 10,
    paddingHorizontal: 10,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  titleInput: {
    fontFamily: globals.normalText.fontFamily,
    fontSize: 18,
    color: "#000",
    marginBottom: 12,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#8d8d8d",
  },
  titleTextInput: {
    fontFamily: globals.normalText.fontFamily,
    color: "#000",
  },
  descriptionInput: {
    marginBottom: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#8d8d8d",
    height: 150,
  },
  descriptionTextInput: {
    fontFamily: globals.normalText.fontFamily,
    color: "#000",
    height: 150,
    paddingHorizontal: 5,
    paddingVertical: 5,
  },
  dateandtimeText: {
    fontFamily: globals.normalText.fontFamily,
    color: "#000",
    marginBottom: 12,
    paddingVertical: 10,
    backgroundColor: "#d8d8d8",
    borderRadius: 10,
    paddingHorizontal: 10,
  },
  pickButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  pickButton: {
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: "rgb(255,204,0)",
  },
  pickButtonText: {
    fontFamily: globals.normalText.fontFamily,
    fontSize: 18,
    color: "#fff",
  },
  bottomButtons: {
    position: "absolute",
    bottom: 10,
    width: "100%",
    alignSelf: "center",
  },
  addButton: {
    backgroundColor: "#00CA4E",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginRight: 10,
    marginBottom: 10,
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  addButtonText: {
    fontFamily: globals.titleText.fontFamily,
    fontSize: 22,
    color: "#fff",
  },
});
